Update terraform_genesys.yml

diff --git a/.github/workflows/terraform_genesys.yml b/.github/workflows/terraform_genesys.yml
--- a/.github/workflows/terraform_genesys.yml
+++ b/.github/workflows/terraform_genesys.yml
@@ -29,10 +29,10 @@ jobs:
       
       - name: Validate secrets are set
         run: |
-          [ -z "${{ secrets.GENESYSCLOUD_OAUTHCLIENT_ID }}" ]     && echo " CLIENT_ID missing"     || echo " CLIENT_ID set"
-          [ -z "${{ secrets.GENESYSCLOUD_OAUTHCLIENT_SECRET }}" ] && echo " CLIENT_SECRET missing" || echo " CLIENT_SECRET set"
-          [ -z "${{ secrets.TF_TOKEN_app_terraform_io }}" ] && echo " TF_TOKEN missing" || echo " TF_TOKEN set"
-          [ -z "${{ secrets.GENESYSCLOUD_REGION }}" ] && echo " Region missing" || echo " TF_TOKEN set"
+          [ -z "$GENESYSCLOUD_OAUTHCLIENT_ID" ]     && echo " CLIENT_ID missing"     || echo " CLIENT_ID set"
+          [ -z "$GENESYSCLOUD_OAUTHCLIENT_SECRET" ] && echo " CLIENT_SECRET missing" || echo " CLIENT_SECRET set"
+          [ -z "$TF_TOKEN_app_terraform_io" ] && echo " TF_TOKEN missing" || echo " TF_TOKEN set"
+          [ -z "$GENESYSCLOUD_REGION " ] && echo " Region missing" || echo " TF_TOKEN set"
         env:
           GENESYSCLOUD_OAUTHCLIENT_ID: ${{ secrets.GENESYSCLOUD_OAUTHCLIENT_ID }}
           GENESYSCLOUD_OAUTHCLIENT_SECRET: ${{ secrets.GENESYS_CLIENT_SECRET }}
@@ -44,9 +44,9 @@ jobs:
         id: criar_genesyscloud
         run: |
           mkdir -p terraform/genesyscloud/flows
-          [ -z "${{ secrets.TF_CLIENT_ID }}" ]     && echo " CLIENT_ID missing"     || echo " CLIENT_ID set"
-          [ -z "${{ secrets.TF_CLIENT_SECRET }}" ] && echo " CLIENT_SECRET missing" || echo " CLIENT_SECRET set"
-          [ -z "${{ secrets.TF_TOKEN_app_terraform_io }}" ] && echo " TF_TOKEN missing" || echo " TF_TOKEN set"
+          [ -z "$GENESYSCLOUD_OAUTHCLIENT_ID" ]     && echo " CLIENT_ID missing"     || echo " CLIENT_ID set"
+          [ -z "$GENESYSCLOUD_OAUTHCLIENT_SECRET" ] && echo " CLIENT_SECRET missing" || echo " CLIENT_SECRET set"
+          [ -z "$TF_TOKEN_app_terraform_io" ] && echo " TF_TOKEN missing" || echo " TF_TOKEN set"
           
       - name: Check for Deleted Files Only
         id: check_changes
